version: "3"
services:
    redis:
        image: redis
        container_name: redis
        restart: always
        ports:
            - 6379:6379

    autograder:
        build: .
        container_name: autograder
        restart: always
        # read_only: true
        tmpfs:
            - /tmp
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        depends_on: 
            - redis
        links:
            - redis:redis-server
        external_links:
            - postgresql
        environment:
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
            - DATABASE_URL=postgresql://postgres:password@postgres/postgres
